export const SET_PRODUCT = 'SET_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';